import pygame
from pygame.locals import *
window = pygame.display.set_mode((600,400))
#
class player(pygame.sprite.Sprite):
    def __init__(self):
        pygame.sprite.Sprite.__init__(self)
        self.image = pygame.image.load('Player.png')
        self.rect = pygame.Rect(0,0,30,30)
player_object = player()
sprites = pygame.sprite.Group()
sprites.add(player_object)


#
loop = True
while loop == True:
    pygame.display.update()
    sprites.draw(window)
    sprites.update()
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            loop = False
pygame.quit()
